#!/bin/bash

# ==============================================
# Author: James Richardson 
# Email: james.richardson@invertedlight.com
# Script Name:
# Date Created:  
# Last Modified:
# Description:
# < Description of what is this script for >
# Usage:
# < How to use this script, flag usage or ... >
# ==============================================

# ============= Start of Code ==================

echo "${PATH//:/$'\n'}"

