#!/bin/bash

# ==============================================
# Author: James Richardson 
# Email: james.richardson@invertedlight.com
# Date Created: 2026-06-26 14:50:29
# Last Modified: 2026-06-26 14:50:29
# Script Name: update_git_repo
# Description:
#  CD to the provided git_repo_DIR (arg1  $1)  to run
#  If no arg provided exit and do nothing, display usage
#  checks git status for missing / changed files
#  executes get status -s to capture the file list
#  executes get commit -m ""  inserting the files that changed
# Usage:
#  update_git_repo git_DIR_path
# ==============================================

# ============= Start of Code ==================
if [ -d $1/.git ]; then
  cd "$1"
  
  repo=$(grep "url" .git/config) | awk -F/ '{print $NF}' | sed 's/\.[^.]*$//'
  
  files=$(git status --short)
    
 echo "$files "

 if [[ -n "$files" ]]; then
    git add .
    git commit -m "Updating repository $repo: $files"
    git push
  fi

  else
    echo "usage: update_git_repo PATH_TO_REPO_DIR"
    echo "No git repo directory path provided exiting"
    exit 1
  fi
